@startuml "docs/images/diagram-01-classes-diagram.png"
!theme plain
hide methods
hide attributes

class Application
class Application::I18n
class Application::Entity
class Application::Camera extends Application::Entity
class Application::Configuration
class Application::PhysicEngine
class Application::CollisionDetector
class Application::Render
class Application::Resources
class Application::ActionHandler

Application "1" --> "1" Application::Camera:activeCamera
Application "1" --> "*" Application::Camera:cameras
Application "1" --> "*" Application::Entity:entities
Application "1" ---> "1" Application::I18n:i18n
Application "1" ---> "1" Application::Resources:resources
Application "1" ----> "1" Application::ActionHandler:ah
Application "1" ---> "1" Application::Configuration:config
Application "1" ----> "1" Application::PhysicEngine:pe
Application "1" ----> "1" Application::CollisionDetector:cd
Application "1" ----> "1" Application::Render:render
@enduml